spring:
  application:
    name: unified-account-domain
  datasource:
    url: jdbc:tc:postgresql:12:///test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8089
  shutdown: graceful
  servlet:
    context-path: /